---
output:
  pdf_document: default
  html_document: default
---
# Final project presentation 1


```{r}
# Load the necessary libraries
library(tidyverse)
library(reshape2)
library(wesanderson)
library(harrypotter)
library(ggpubr)
library(tagger)

library(tidyr)
library(dplyr)

```


```{r}
# Load the gene expression data and metadata
GeneExpression_data<- read.csv(file = "/Users/Student1/Downloads/QBS103_finalProject_geneExpression.csv")
Metadata<- read.csv(file =  "/Users/Student1/Downloads/QBS103_finalProject_metadata.csv")

# Loak at both the csv files using head function

head(GeneExpression_data)
head(Metadata)

```

```{r}
# Rename the first column of GeneExpression_data
colnames(GeneExpression_data) [1]<- "Genes"

# Check the renaming

head(GeneExpression_data)

```

```{r}
# Convert the gene expression data into long format
longData<- reshape2::melt(GeneExpression_data, id.vars = ("Genes"),
                          value.name = "gene_expression", variable.name = "participant_id")

# Check the long format conversion

head(longData)

```

```{r}
# Link longData with Metadata

LinkedData<- merge(longData, Metadata, by = "participant_id")

# View the linked data

head(LinkedData)
tail(LinkedData)

```


# Identify one gene, one continuous covariate, and two categorical covariates in the provided dataset

# One gene - CD24
# One continuous covariate - age
# Two categorical covariates - sex, mechanical_ventilation

## Generate the following plots using ggplot2 for your covariates of choice:
```{r}

# Histogram for gene expression

# I selected the CD24 gene for my plots
# Now, subset LinkedData for CD24 gene expression

CD24_expression<- LinkedData[LinkedData$Genes == "CD24", ]

# Define a theme for my plots

MyTheme <- theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(color = "black", linewidth = rel(1)), plot.background = element_rect(fill = "white"), panel.background = element_blank(), legend.key = element_rect(fill = "white"), legend.position = "right")

# Calculating mean, standard deviation to display on histogram

MeanCD24 <- round(mean(CD24_expression$gene_expression), digits = 1)
SDCD24<- round(sd(CD24_expression$gene_expression), digits = 1)


# Now Generate histogram for CD24 expression
Histogram<- ggplot(CD24_expression) +
  geom_histogram(aes(gene_expression),bins = 20, color = "black", fill = "firebrick3")+
  labs(x = "Expression", y  = "Frequency")+
  MyTheme +
  annotate(geom = "text", x = 200, y = 63, label = paste("The Mean(SD) Expression Level of CD24 Gene",":", MeanCD24,"(", SDCD24,")"), color ="black")
  


plot(Histogram)

```

```{r}
# Scatterplot for gene expression and continuous covariate
# Here, I selected age as the continuous covariate
# To show the expression pattern, I created an age group. Here, I used some code suggestions from community.rstudio.

# First change age >89 values to age =  90
CD24_expression$age[CD24_expression$age==" >89"]<- "90"

# Check the change of the value
CD24_expression$age

# Convert age values from character to numeric values
CD24_expression$age<- as.numeric(CD24_expression$age)

# Create age_group category in CD24_expression dataframe
CD24_expression<- CD24_expression %>% 
  mutate(
    # Create a category named age_group
    age_group = dplyr::case_when(
      age<=29          ~"0-29",
      age>29 & age<=49  ~"30-49",
      age> 49 & age<=69  ~ "50-69",
      age> 69 & age<=89 ~"70-89",
      age>89          ~"> 89"),
   # Converting age_group to factor
    age_group = factor(
      age_group,
      level = c("0-29", "30-49","50-69","70-89", "> 89")
     ))
    
# Check the inclusion of age_group
CD24_expression$age_group

# Now, create a colorpalette

ColorPalette_scatter<- c ("firebrick3", "pink", "blue3", "purple", "gold")

# Calculating mean, standard deviation for the variable age

MeanAge <- round(mean(CD24_expression$age), digits = 1)
MedianAge<- round(median(CD24_expression$age), digits = 1)

# Generate the scatterplot
Scatterplot <- ggplot(CD24_expression, aes(x = age, y = gene_expression, color = age_group))+
  geom_point()+
  MyTheme+
  scale_color_manual(values = ColorPalette_scatter, name = "Age Group")+
  labs(title = "The association of CD24 expression and age", x = paste("Age", "(", "mean", "=", MeanAge,",", "median","=", MedianAge,")"), y = "CD24 expression")


plot(Scatterplot)


```

```{r}
# Boxplot of gene expression separated by both categorical covariates.
# For the two categorical covariates, I have selected sex and mechanical_ventilation

# Calculate the number of each sex
table(CD24_expression$sex)

# calculate the number for ventilation or not
table(CD24_expression$mechanical_ventilation)

# First, create a colorpalette for this plot
colorpalette_boxplot<- harrypotter::harrypotter(n = 2, house = "Ravenclaw")

# Now, generate the boxplot
Boxplot <- ggplot(CD24_expression, aes(x = sex, y = gene_expression, fill = CD24_expression$mechanical_ventilation))+
  geom_boxplot() +
  MyTheme+
  scale_fill_manual (values = colorpalette_boxplot, name = "Mechanical Ventilation", labels = c("No(74)", "Yes(51)"))+
  labs(title = "The Association CD24 Expression With Sex And Mechanical Ventilation", y = "CD24 Expression")+
  scale_x_discrete(name = "Sex", labels =c( "Female(51)", "Male(73)", "Unknown(1)"))
  
plot(Boxplot)

```

 

