---
title: "Final project presentation 3"
author: "sadia kana"
date: "2023-08-14"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Final project presentation 3

```{r}
# Load the necessary libraries
library(tidyverse)
library(reshape2)
library(wesanderson)
library(harrypotter)
library(ggpubr)
library(tagger)

library(tidyr)
library(dplyr)
library(pheatmap)
library(knitr)
library(kableExtra)
library(gganimate)
library(gapminder)
library(gifski)
library(knitr)
library(kableExtra)

```


```{r}
# Load the gene expression data and metadata
GeneExpression_data<- read.csv(file = "/Users/Student1/Downloads/QBS103_finalProject_geneExpression.csv")
Metadata<- read.csv(file =  "/Users/Student1/Downloads/QBS103_finalProject_metadata.csv")


# Loak at both the csv files using head function

  head(GeneExpression_data)
  head(Metadata)
```

```{r}
# Rename rownames of GeneExpression_data and Metadata
rownames(GeneExpression_data) <- GeneExpression_data$X
rownames(Metadata)<- Metadata$participant_id

# Check the renaming
 rownames(GeneExpression_data)
 rownames(Metadata)
 
 # Remove the x column from gene expression data and participant_id from Metadata
 GeneExpression_data<- GeneExpression_data[, -1]
 Metadata<- Metadata[, -1]
 
```



```{r}
# Now, subset GeneExpression data for CD24 gene
CD24Expression<- GeneExpression_data["CD24", ]

# Convert row to column in the Geneexpression data and CD24Expression
geneT_data<- as.data.frame(t(GeneExpression_data))
CD24Expression<- as.data.frame(t(CD24Expression))

# Check the transformed version
  head(geneT_data)
  head(CD24Expression)
  
# Now, calculate the variance for all genes in geneT_data
variance<- apply(geneT_data, MARGIN = 2, FUN = var)

# Organize the geneT_data according to the variance (highest to lowest)
geneT_data<- geneT_data[, order(variance, decreasing = T)]

# Now, subset the geneT_Data for first 15 genes
Heatmap_geneset<- geneT_data[, 1:15]

```

```{r}
# Link CD24Expression and Heatmap_geneset with Metadata

CD24Expression<-cbind(CD24Expression, Metadata)
Heatmap_geneset<- cbind(Heatmap_geneset, Metadata)


# View theCD24Expression and Hetamap_geneset

  head(CD24Expression)
  head(Heatmap_geneset)
  
  
# Now clean the data
# Remove unknown values from CD24Expression and Heatmap_geneset
   
CD24Expression<- CD24Expression[apply(CD24Expression, 1, function(x) all(x != "unknown")), ]
CD24Expression<- droplevels(na.omit(CD24Expression))
  
Heatmap_geneset<- Heatmap_geneset[apply(Heatmap_geneset, 1, function(x) all(x != "unknown")), ]
Heatmap_geneset<- droplevels(na.omit(Heatmap_geneset))

```


# Generate plots incorporating the feedback
```{r}

# The data frame - CD24Expression
# A continuous covariate is "age"
# Two categorical covariates are "sex",  and "mechanical_ventilation"


# Now generate a theme
  MyTheme <- theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(color = "black", linewidth = rel(1)), plot.background = element_rect(fill = "white"), panel.background = element_blank(), legend.key = element_rect(fill = "white"), legend.position = "right")
  

# Select and onvert the continous covariate into numeric form
  CD24Expression$age <- as.numeric(CD24Expression[["age"]])

# Calculating mean, standard deviation for continuous covariate
MeanAge <- round(mean(CD24Expression$age, na.rm = T))
MedianAge<- round(median(CD24Expression$age, na.rm = T))
  
# Creating histogram
Histogram<- ggplot( CD24Expression) +
  geom_histogram(aes(CD24),bins = 20, color = "azure2", fill = "aquamarine4")+
  labs(x = substitute(paste(italic(CD24)," ", "expression")), y  = "Participant number")+
  MyTheme +
  theme(text = element_text(size = 10))+
  geom_vline(aes(xintercept = median(CD24Expression$CD24)), color = "magenta1", size = .8) +
  theme(plot.title = element_text(hjust = .35))+
  ggtitle(label =substitute(paste("The Expression Level of"," ", italic(CD24)," ", "gene")), subtitle = "Vertical line indicates median value")+
  theme(plot.subtitle = element_text(color = "magenta1"))
  
plot(Histogram)

# Generate the scatterplot
Scatterplot <- ggplot( CD24Expression, aes(x = age, y = CD24))+
  geom_point(color = "aquamarine4", alpha = .6, size = 3)+
  MyTheme+
  labs(title = substitute(paste("The association of ", italic(CD24)," ", "expression and"," ", "age")) ,x = paste("Age in yrs", "(", "mean", "=", MeanAge,",", "median","=", MedianAge,")"), y = substitute(paste(italic(CD24)," ", "expression")))+
  theme(text = element_text(size = 11)) + 
  theme(plot.title = element_text(hjust = .35))

plot(Scatterplot)

# Now, generate the boxplot

Boxplot <- ggplot( CD24Expression, aes(x = sex, y = CD24, fill = mechanical_ventilation))+
  geom_boxplot() +
  MyTheme+
  scale_fill_manual(values = c("deepskyblue","aquamarine4"),name = "Mechanical ventilation", labels = c("No(75)", "Yes(51)"))+
  labs(title = substitute(paste("The association of ", italic(CD24)," ", "expression with sex and mechanical ventilation")), y = substitute(paste(italic(CD24)," ", "Expression")))+
  scale_x_discrete(name = "Sex", labels =c( "Female(51)", "Male(74)"))+
  theme(text = element_text(size = 10))


#Boxplot<- Box + str_to_title()
plot(Boxplot)


```


```{r}

# Creating a function for the summary table. Using code suggestions from classwork solution

Table1 <- function(data,varList,nonnormVars = '',catVars = '') {
  
  # Define an empty table
  table1 <- matrix(nrow = 0,ncol = 2)
  # Keep track of rows to indent
  indentRows <- c()
  
  # Loop through all variables
  for (var in varList) {
    
    # Define vector of variable values
    x <- data[,var]
    
    # Identify if non-normal
    if (var %in% nonnormVars) {
      
      # Calculate individual values
      myMedian <- round(median(as.numeric(x), na.rm = T))
      myIQR1 <- round(quantile(as.numeric(x),1/4, na.rm = T),digits = 2)
      myIQR2 <- round(quantile(as.numeric(x),3/4, na.rm = T),digits = 2)
      # Combine values
      value <- paste0(myMedian,' [',myIQR1,', ',myIQR2,']')
      
      # Define new row
      newRow <- c(paste0('**',var,'** Median [IQR]'),value)
      
      # Add row to data frame
      table1 <- rbind(table1,newRow)
      
    }
    
    # Identify if categorical
    if (var %in% catVars) {
      
      # Define new row for overall variable
      newRow <- c(paste0('**',var,'** n (%)'),'')
      # Add row to data frame
      table1 <- rbind(table1,newRow)
      
      # Loop through levels of variable
      for (level in levels(as.factor(x))) {
        # Calculate n and perc
        n <- sum(x == level)
        perc <- round(n/(length(x)) * 100,digits = 2)
        
        # Combine values
        value <- paste0(n,' (',perc,')')
        
        # Define new row
        newRow <- c(level,value)
        # Add row to data frame
        table1 <- rbind(table1,newRow)
        # Add index to indented rows
        indentRows <- c(indentRows,nrow(table1))
        
        
      }
    }
    
    # Otherwise treat as normally distributed
    if (!(var %in% c(nonnormVars,catVars))) {
      
      # Calculate individual values
      myMean <- round(mean(as.numeric(x), na.rm = T),2)
      mySD <- round(sd(as.numeric(x), na.rm = 2),2)
      # Combine values
      value <- paste0(myMean,' (',mySD,')')
      
      # Define new row
      newRow <- c(paste0('**',var,'** Mean (sd)'),value)
      
      # Add row to data frame
      table1 <- rbind(table1,newRow)
      
    }
  }
  
  # Define sample size for heading
  sampleSize <- paste("n =",nrow(data))
  
  # Print formatted table
  kable(x = table1, caption = 'Table 1',
        col.names = c("Variable",sampleSize),
        align = c('l','r'),escape = T,row.names = F) %>%
    add_indent(positions = indentRows) %>%
    kable_classic()
    
}
CD24Expression$lactate.mmol.l.
# Table rows  = Age,Sex, Ferritin, Mechanical ventilation, Procalcitonin, Icu status, Lactate 

Table1(CD24Expression, varList = c("age","sex","ferritin.ng.ml.","mechanical_ventilation","procalcitonin.ng.ml..", "icu_status", "lactate.mmol.l."), nonnormVars = c("age","ferritin.ng.ml.","procalcitonin.ng.ml..", "lactate.mmol.l."), catVars = c("sex", "mechanical_ventilation", "icu_status"))


```



```{r}

# Now, log2 normalize all gene columns from Heatmap_geneset
i<- c(1:15)
Heatmap_geneset[ , i] <- apply(Heatmap_geneset[ , i], 2,           
                    function(x) log2(x))

# Remove any rows with inf values (code suggestion from stackoverflow.com. I have customized the code for my dataset
Heatmap_geneset %>% 
  rowwise %>% 
  filter(!any(is.infinite(c_across(where(is.numeric)))))

# Removing NaN from Heatmap_geneset rows
geneset<- na.omit(Heatmap_geneset)

# Remove unwanted columns from Heatmap_geneset
geneset<- geneset[, -(c((16:25), (27:29), (31:39)))]

# Creating annotation data and annotation colors for heatmaps

annotationData <- data.frame(row.names = rownames(geneset),
                             'Sex' = factor(geneset$sex, labels = c("Female", "Male")),
                             'Mechanical Ventilation' = factor(geneset$mechanical_ventilation, labels = c("No", "Yes")))

# Define color palette
annotationColors <- list(Sex = c('Female' = 'royalblue4',
                                 'Male' = 'magenta4'),
                         Mechanical.Ventilation = c("No" = "pink",
                                                   "Yes" = "blue" ) )

##
geneset<- na.omit(geneset)
# Generate heatmaps with clustering by euclidean algorithm and tracking bar for sex or mechanical ventilation

pheatmap(geneset[, 1:15],
         fontsize_row = 4,
         fontsize_col = 8,
         clustering_distance_rows = 'euclidean',
         clustering_distance_cols = 'euclidean',
    annotation_row = annotationData,
    annotation_colors =annotationColors,
    main = "Gene expression clustered by euclidean algorithm")


```



#Going through the documentation for ggplot2, generate a plot type that we did not previously discuss in class that describes your data in a new and unique way

```{r}

# Convert ferritin into numeric form
CD24Expression$ferritin.ng.ml.<- na.omit(as.numeric(CD24Expression$ferritin.ng.ml.))

# Create geom_hexagon plot using ggplot2

g<- ggplot(CD24Expression, aes( x = ferritin.ng.ml., y =CD24))+
  geom_hex(bins = 30, colour = "white")+
  theme_classic()+
  labs(title =substitute(paste( "The association of ", italic("CD24")," ", "expression with ferritin")), x = "Ferritin", y =substitute(paste(italic("CD24"), " ","expression")))+
  theme(text = element_text(size = 11)) + 
  theme(plot.title = element_text(hjust = .35))

plot(g)

```

  
  
  




